=pod

=begin html

<link rel="stylesheet" href="podstyle.css" type="text/css" />

=end html

=head1 NAME

lmcurve - Levenberg-Marquardt least-squares curve fitting


=head1 SYNOPSIS

B<#include <lmcurve.h>>

B<void lmcurve( int> I<n_par>B<, double *>I<par>B<, int> I<m_dat>B<,
              constS< >double *>I<t>B<, constS< >double *>I<y>B<,
              double (*>I<f>B<)( double >I<ti>B<, const double *>I<par>B< ),
              constS< >lm_control_struct *>I<control>B<,
              constS< >lm_princon_struct *>I<princon>B<,
              lm_status_struct *>I<status>B<);>

B<extern const lm_control_struct lm_control_double;>

B<extern const lm_control_struct lm_control_float;>

B<extern const lm_princon_struct lm_princon_std;>

B<extern const char *lm_infmsg[];>

B<extern const char *lm_shortmsg[];>

=head1 DESCRIPTION

B<lmcurve()> determines a vector I<par> that minimizes the sum of squared elements of a residue vector I<r>[i] := I<y>[i] - I<f>(I<t>[i];I<par>). Typically, B<lmcurve()> is used to approximate a data set I<t>,I<y> by a parametric function I<f>(I<ti>;I<par>). On success, I<par> represents a local minimum, not necessarily a global one; it may depend on its starting value.

Function arguments:

=over

=item I<n_par>

Number of free variables. Dimension of parameter vector I<par>.

=item I<par>

Parameter vector. On input, it must contain a reasonable guess; on output, it contains the solution found to minimize ||I<r>||.

=item I<m_dat>

Number of data points. Dimension of vectors I<t> and I<y>.

=item I<t>

Array of length I<m_dat>.
Contains the abcissae (time, or "x") for which function I<f> will be evaluated.

=item I<y>

Array of length I<m_dat>.
Contains the ordinate values that shall be fitted.

=item I<f>

A user-supplied parametric function I<f>(ti;I<par>).

=item I<control>

A record holding auxiliary parameters that control the fit procedure.
In most cases, the default &I<lm_control_double> is adequate.
If I<f> is only computed with single-precision accuracy,
I<&lm_control_float> should be used.
For fine tuning, see B<lmfit(7)>.

=item I<princon>

A record holding auxiliary parameters to control verbosity of the fit.
For values NULL or &I<lm_princon_def>, the fit is silent.
To obtain progress messages, see B<lmfit(7)>.

=item I<status>

A record used to return information about the minimization process:

=over

=item B<double> I<status.fnorm>

norm of the residue vector I<r>;

=item B<int> I<status.nfev>

actual number of iterations;

=item B<int> I<status.info>

status of minimization;
for the corresponding text message, print I<lm_infmsg>B<[>I<status.info>B<]>;
for a short code, print I<lm_shortmsg>B<[>I<status.info>B<]>.

=back

=back


=head1 EXAMPLE

    #include "lmcurve.h"
    #include <stdio.h>

    /* model function: a parabola */

    double f( double t, const double *p )
    {
        return p[0] + p[1]*t + p[2]*t*t;
    }

    int main()
    {
        int n = 3; /* number of parameters in model function f */
        double par[3] = { 100, 0, -10 }; /* really bad starting value */

        /* data points: a slightly distorted standard parabola */
        int m = 9;
        int i;
        double t[9] = { -4., -3., -2., -1.,  0., 1.,  2.,  3.,  4. };
        double y[9] = { 16.6, 9.9, 4.4, 1.1, 0., 1.1, 4.2, 9.3, 16.4 };

        lm_status_struct status;

        printf( "Fitting ...\n" );
        lmcurve( n, par, m, t, y, f, &lm_control_double, NULL, &status );

        printf( "Results:\n" );
        printf( "status after %d function evaluations:\n  %s\n",
                status.nfev, lm_infmsg[status.info] );

        printf("obtained parameters:\n");
        for ( i = 0; i < n; ++i)
            printf("  par[%i] = %12g\n", i, par[i]);
        printf("obtained norm:\n  %12g\n", status.fnorm );

        printf("fitting data as follows:\n");
        for ( i = 0; i < m; ++i)
            printf( "  t[%2d]=%4g y=%6g fit=%10g residue=%12g\n",
                    i, t[i], y[i], f(t[i],par), y[i] - f(t[i],par) );

        return 0;
    }

=head1 VERSIONS

The first public release was 2.0 (December 2004). The API has changed with version 3.0 (March 2010), and again with version 4.0 (July 2013).


=head1 COPYING

Copyright (C) 2009-2013 Joachim Wuttke, Forschungszentrum Juelich GmbH

Software: FreeBSD License

Documentation: Creative Commons Attribution Share Alike


=head1 SEE ALSO

B<lmfit(7)>, B<lmmin(3)>.

Main web site: http://apps.jcns.fz-juelich.de/lmfit

Fallback web link: http://joachimwuttke.de/lmfit

Please report bugs to the author <j.wuttke@fz-juelich.de>


=begin html

<img src="http://vg06.met.vgwort.de/na/d504226082098fdbc96b0cdf2054ba"
     width="1" height="1" alt="">

=end html
