jobs:
  - job: 'BuildLib'
    pool:
        vmImage: 'ubuntu-latest'
    steps:
        - task: UsePythonVersion@0
          inputs:
              versionSpec: '3.6'
              architecture: 'x64'
        - script: |
            sudo apt-get install cmake
            python -m pip install cpplint
          displayName: Install Deps
        - script: |
            cmake --version
            mkdir lmfit_build
            cd lmfit_build
            cmake -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_POSITION_INDEPENDENT_CODE=YES \
            -DCMAKE_INSTALL_PREFIX=/usr \
            ..
            make
          displayName: Build and Install lmfit

