#!/bin/sh

# convert pod documentation into man page and into html
# (only needed by the maintainer; output files are part of the distribution)

#pod2man -s 3 -c "lmfit manual" lmmin.pod > lmmin.3
pod2man -s 3 -c "lmfit manual" lmfit.pod > lmfit.3

#pod2html --title="LMMIN(3) --- Levenberg-Marquardt minimization and curve fitting" --noindex lmmin.pod > lmmin.html
pod2html --title="LMFIT(3) --- Levenberg-Marquardt minimization and curve fitting" --noindex lmfit.pod > lmfit.html
